ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys-prod/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys-prod/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys-prod/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys-prod/refresh-token-public.key"
KEY_PATH: "access-refresh-token-keys-prod"
